const TeacherActionTypes = {
    FETCH_TEACHERS_START: 'FETCH_TEACHERS_START',
    FETCH_TEACHERS_SUCCESS: 'FETCH_TEACHERS_SUCCESS',
    FETCH_TEACHERS_FAILURE: 'FETCH_TEACHERS_FAILURE',
    RESET_TEACHERS: 'RESET_TEACHERS'
};

export default TeacherActionTypes;