const LessonPlanActionTypes = {
    SET_LESSON_PLAN_CHECKS_START: 'SET_LESSON_PLAN_CHECKS_START',
    SET_LESSON_PLAN_CHECKS_SUCCESS: 'SET_LESSON_PLAN_CHECKS_SUCCESS',
    SET_LESSON_PLAN_CHECKS_FAIL: 'SET_LESSON_PLAN_CHECKS_FAIL',
    SUBMIT_LESSON_PLAN_CHECK_START: 'SUBMIT_LESSON_PLAN_CHECK_START',
    SUBMIT_LESSON_PLAN_CHECK_SUCCESS: 'SUBMIT_LESSON_PLAN_CHECK_SUCCESS',
    SUBMIT_LESSON_PLAN_CHECK_FAIL: 'SUBMIT_LESSON_PLAN_CHECK_FAIL',
    RESET_LESSON_PLAN_CHECKS: 'RESET_LESSON_PLAN_CHECKS'
}

export default LessonPlanActionTypes;