export const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_SCHOOL_PREFERENCE: 'SET_SCHOOL_PREFERENCE',
    SET_DEPARTMENT_PREFERENCE: 'SET_DEPARTMENT_PREFERENCE',
    SET_ACTIVE_TEACHER_PREFERENCE: 'SET_ACTIVE_TEACHER_PREFERENCE'
}